### ISSUE TITLE
Passing an invalid bitcode file results in an error that can't be handled by callee

### ISSUE THREAD

**Issue by notmgsk** [cdisselkoen/llvm-ir#12]
It seems that if you call `llvm_ir::Module::from_bc_path()` with a path to a file that does not contain valid bitcode, an error occurs which cannot be handled at the call site. Instead the program panics without a backtrace and with the message "error: Invalid bitcode signature". The signature of `from_bc_path` would lead one to believe that it returns errors that _can_ be handled as a typical rust error.

**Comment by cdisselkoen** [comment]
Unfortunately, I think this is the fault of our dependency [`llvm-sys`] - I'm guessing this message probably occurs during the call to `LLVMParseBitcodeInContext2` [here](https://github.com/cdisselkoen/llvm-ir/blob/e3cf1f131a6ff853b3d837d5706dd82411cac5ba/src/module.rs#L90).  I recommend you file an issue on [`llvm-sys`].

[`llvm-sys`]: https://gitlab.com/taricorp/llvm-sys.rs

**Comment by cdisselkoen** [comment]
I'm going to go ahead and close this, as it's not something that's fixable inside `llvm-ir`.  We still want `from_bc_path` to return a `Result`, for the errors that it _can_ let callers handle as a typical Rust error.
