### ISSUE TITLE
New release for support LLVM 13

### ISSUE THREAD

**Issue by aleasims** [cdisselkoen/llvm-ir#19]
First of all thanks a lot for this crate!

Current latest release (`v0.8.1`) does not contain some recent changes on supporting LLVM 13 (like this #17). Also docs in this release are still referencing to LLVM 12. Is it possible to release `v0.8.2` containing all changes already made since then?

**Comment by cdisselkoen** [comment]
Just released v0.8.2 including LLVM 14 support as well.  Please feel free to reopen if this hasn't addressed the issue.
