### ISSUE TITLE
The `Name` field of `GlobalReference` could be a `String`

### ISSUE THREAD

**Issue by langston-barrett** [cdisselkoen/llvm-ir#23]
The `GlobalReference` constant has a `Name` field, where `Name` is a sum of `u64` and `String`. I *believe* global variables and functions always have actual names, rather than numbers - perhaps the `Name` field of `GlobalReference` could be specialized to `String`?

**Comment by cdisselkoen** [comment]
You are right.  Let's specialize

**Comment by cdisselkoen** [comment]
Reverted this after discussion on #42.
