### ISSUE TITLE
The `Name` field of `GlobalVariable` could be a `String`

### ISSUE THREAD

**Issue by langston-barrett** [cdisselkoen/llvm-ir#26]
Same comment as #23, global variables always have actual names.

**Comment by cdisselkoen** [comment]
Does the resolution of #23 (1c53f8ac) not address the issue?

**Comment by cdisselkoen** [comment]
Thanks for this report.  Fixed on `main` now

**Comment by cdisselkoen** [comment]
Reverted this after discussion on #42.
