### ISSUE TITLE
Function declarations

### ISSUE THREAD

**Issue by langston-barrett** [cdisselkoen/llvm-ir#28]
[`Module.functions`](https://docs.rs/llvm-ir/0.8.2/llvm_ir/module/struct.Module.html#structfield.functions) contains only the functions defined in the module, and it doesn't look like there's anywhere else to get the declared functions. This is an issue for certain analyses that need e.g., parameter types for declared functions.

A reasonable way to add this to the API would be to add a new field (`declarations`?) to `Module` of type `Vec<Declaration>` for some struct `Declaration` that shares most of the fields of `Function`.

**Comment by cdisselkoen** [comment]
Great suggestion.  Added this on `main`
