### ISSUE TITLE
Indexed type of `GetElementPtr`

### ISSUE THREAD

**Issue by langston-barrett** [cdisselkoen/llvm-ir#32]
As noted in [the docs](https://releases.llvm.org/14.0.0/docs/LangRef.html#getelementptr-instruction):

> The interpretation of each index is dependent on the type being indexed into.

One can't calculate, e.g., the offset that the GEP adds to the pointer without knowing which type it is indexing at. The solution is probably just to add a `indexed_type: TypeRef` field to [`GetElementPtr`](https://github.com/cdisselkoen/llvm-ir/blob/4a9f1fb4c8421e3117e8a6e589e00d964e6394d9/src/instruction.rs#L1552).

This would enable a method like LLVM's [`accumulateConstantOffset`](https://llvm.org/doxygen/classllvm_1_1GetElementPtrInst.html#acd203d07a075c5a33492609ef8f3643e), which would be quite useful for my purposes!

**Comment by cdisselkoen** [comment]
In LLVM 14 and below, I believe that you can get the type information you need by looking at the type of the `address` field of the `GetElementPtr`.  Or am I misunderstanding?

**Comment by langston-barrett** [comment]
> In LLVM 14 and below, I believe that you can get the type information you need by looking at the type of the address field of the GetElementPtr.

I'm not sure whether it's an invariant that the operand is always of the same type being indexed. Semantically, one could imagine indexing into any `T*` as if it were a `i8*`. If this is an invariant, then it does indeed solve my problem for LLVM <15.

**Comment by cdisselkoen** [comment]
In LLVM <15, yes, the types are required to match there, and explicit cast operations are required if it doesn't.  For more on this topic see the [discussion on why LLVM 15 moved to opaque pointers](https://releases.llvm.org/15.0.0/docs/OpaquePointers.html).

**Comment by cdisselkoen** [comment]
Going to close this, feel free to reopen if needed.
