### ISSUE TITLE
Linking fails with LLVM 12

### ISSUE THREAD

**Issue by deepaksirone** [cdisselkoen/llvm-ir#35]
Hello,

It seems that LLVM 12 does not have the functions LLVMIsTypeAttribute and LLVMGetTypeAttributeValue defined in the source code (https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/llvm-12.0.0.src.tar.xz). Building with `cargo build --features llvm-12` creates a library with both these symbols as undefined and causes a linking error when trying to link against llvm 12.
```
nm libllvm_ir.rlib | less
                 U LLVMGetAlignment
                 U LLVMGetAttributeCountAtIndex
                 U LLVMGetAttributesAtIndex
                 U LLVMGetComdat
                 U LLVMGetDLLStorageClass
                 U LLVMGetElementType
                 U LLVMGetEnumAttributeKind
                 U LLVMGetEnumAttributeValue <--
                 U LLVMGetFunctionCallConv
                 U LLVMGetLinkage
                 U LLVMGetPersonalityFn
                 U LLVMGetReturnType
                 U LLVMGetTypeAttributeValue
                 U LLVMGetVisibility
                 U LLVMHasPersonalityFn
                 U LLVMIsAFunction
                 U LLVMIsEnumAttribute
                 U LLVMIsFunctionVarArg
                 U LLVMIsStringAttribute
                 U LLVMIsTypeAttribute <---
                 U LLVMTypeOf
```

The cause seems to the feature flags in src/function.rs (https://github.com/cdisselkoen/llvm-ir/blob/main/src/function.rs#L847) and (https://github.com/cdisselkoen/llvm-ir/blob/main/src/function.rs#L874) referring to both these symbols with the llvm-12 feature enabled.

Both the functions seem to be present from LLVM 13 onwards.

**Comment by cdisselkoen** [comment]
All tests pass for me with LLVM 12.  Do tests fail for you?

We only support the latest point-release of each LLVM major version, so that means LLVM 12.0.1 rather than 12.0.0.  If you test with 12.0.1 does that make a difference?

Another thing you should try is `--features llvm-12-strict`.  The `-strict` ensures you link against _exactly_ LLVM 12.  Without `-strict`, it may try to link against other LLVM versions it thinks may be compatible.

**Comment by deepaksirone** [comment]
Hello, sorry for the late response. Yes, the issue does not appear with LLVM 12.0.1 . Thanks for your response
