### ISSUE TITLE
Global variables can be named with numbers

### ISSUE THREAD

**Issue by matklad** [cdisselkoen/llvm-ir#42]
I am trying to use `llvm-ir` to analyse some code compiled by `zig`, and I get this error message:

```
Expected global variable or function to have a real name, not a number 7
```

The message is the same for either .bc or .ll. In my .ll I have

```ll
@7 = internal unnamed_addr constant %"[]u8" { i8* getelementptr inbounds ([25 x i8], [25 x i8]* @6, i64 0, i64 0), i64 24 }, align 8
```

So it looks like a number is actually a valid name?

**Comment by matklad** [comment]
Full code here: 

https://gist.github.com/matklad/97b9a754a4b5c5a1687bc8ab946489e3

And here's how I try to load this:

```rust
    let module = llvm_ir::Module::from_ir_path(path)
        .map_err(|err| anyhow::format_err!("failed to load {}: {err}", path.display()))?;
    eprintln!(
        "Loaded module from {} with {} functions",
        path.display(),
        module.functions.len()
    );
```

**Comment by cdisselkoen** [comment]
Interesting, you seem to have a disagreement with @langston-barrett who opened #23 and #26. My reading of the LLVM Language Reference agreed with @langston-barrett so I changed the behavior, but your evidence is pretty convincing

**Comment by cdisselkoen** [comment]
Investigated the LLVM code some more and I now believe GlobalValue/Variable/Alias can have numbers, not necessarily string names, even if the LLVM language reference is not clear.  I will revert #23, #26, and #33.
