### ISSUE TITLE
Are optimization passes implemented?

### ISSUE THREAD

**Issue by ManicMarrc** [cdisselkoen/llvm-ir#47]
LLVM has these [Passes](https://www.llvm.org/docs/Passes.html) that can optimize the generated IR.
I'm wondering if these are implemented as I can't seem to find them in the documentation.

**Comment by cdisselkoen** [comment]
We don't have any optimization passes implemented here -- in general I would recommend optimizing your IR first using LLVM itself, and then loading it into this library.  The representation in this library would be less convenient for implementing optimizations than the representation LLVM uses internally.

**Comment by cdisselkoen** [comment]
Closing this as answered-question.  Feel free to reopen to continue the discussion
