### ISSUE TITLE
Support for LLVM 17

### ISSUE THREAD

**Issue by woodruffw** [cdisselkoen/llvm-ir#48]
Looks like `rustc` bumped up to LLVM 17, starting with 1.73.0.

I'll try and get a PR opened for this in the coming days.

**Comment by apps4uco** [comment]
Hi, any news on this. +1 votes for this ;)

**Comment by woodruffw** [comment]
> Hi, any news on this. +1 votes for this ;)

None from me, sorry. I was hoping to get started on this, but I haven't had the time.

**Comment by R9295** [comment]
I will give this a shot but would love any pointers and obvious gotchas.

**Comment by cdisselkoen** [comment]
Closing this as #55 has been merged, providing support for LLVM 17 (current tests pass).  If there are important shortcomings / things missing, please reopen this issue or open a new one
