### ISSUE TITLE
Panic while parsing in llvm-ir-0.10.0/src/constant.rs:1503

### ISSUE THREAD

**Issue by bitmagier** [cdisselkoen/llvm-ir#57]
`llvm-ir = { version = "0.10.0", features = ["llvm-16"] }` 

Parsing bitcode file, created from clang-16 compiled glibc file "string/strstr.c" panics.
(repo: https://sourceware.org/git/glibc.git, branch azanella/clang)

```log
2024-01-27T19:04:16.836+01:00 DEBUG [llvm_ir::module] Processing a GlobalVariable with type TypeRef(PointerType { addr_space: 0 })
thread 'main' panicked at /home/bitmagier/.cargo/registry/src/index.crates.io-6f17d22bba15001f/llvm-ir-0.10.0/src/constant.rs:1503:103:
Global not found in ctx.global_names; have names [Name("llvm.lifetime.start.p0"), Name("__strstr_sse2_unaligned"), Name("__strstr_generic"), Name("llvm.dbg.declare"), Name("__strstr_avx512"), Name("bcmp"), Name("__strnlen"), Name("strlen"), Name("two_way_long_needle"), Name("__libc_strstr_ifunc"), Name("strstr"), Name("llvm.dbg.value"), Name("strchr"), Name("llvm.memset.p0.i64"), Name("llvm.lifetime.end.p0"), Name("llvm.umax.i64"), Name("SYMBOL_NAME_ifunc_selector"), Name("_dl_x86_cpu_features")]
```

Bitcode: [strstr.o.bc.gz](https://github.com/cdisselkoen/llvm-ir/files/14073339/strstr.o.bc.gz)
Full Log: [trace.log](https://github.com/cdisselkoen/llvm-ir/files/14073354/trace.log)

**Comment by Benjins** [comment]
I confirmed this repros on the latest trunk, w/ llvm-16 of llvm-17. Using llvm-reduce, I got this minimal repro:
```llvm
@strstr = alias ptr (ptr, ptr), ptr @__libc_strstr

@__libc_strstr = ifunc ptr (ptr, ptr), ptr @__libc_strstr_ifunc

define internal ptr @__libc_strstr_ifunc() {
  ret ptr null
}
```

It looks like we don't currently handle `ifunc` globals: https://llvm.org/docs/LangRef.html#ifuncs

**Comment by cdisselkoen** [comment]
#61 adds support for `ifunc`s.
