### ISSUE TITLE
New release for LLVM 17?

### ISSUE THREAD

**Issue by woodruffw** [cdisselkoen/llvm-ir#59]
Hello! As always, thanks a ton for maintaining `llvm-ir`!

Now that #55 is merged, it'd be great to have a release that includes the `llvm-17` feature 🙂

**Comment by cdisselkoen** [comment]
Will do shortly.  I'd like to get some other changes into the next release (that would be breaking if we did them after the release), such as #56 and #58.

**Comment by cdisselkoen** [comment]
Also #60 (assuming there are no objections).

**Comment by cdisselkoen** [comment]
Also #61 while we're at it.  (Adding a field to `Module` is a semver breaking change.)

**Comment by cdisselkoen** [comment]
Released 0.11.0
