### ISSUE TITLE
Version 0.7 and pattern matching

### ISSUE THREAD

**Issue by TheZoq2** [cdisselkoen/llvm-ir#6]
I started bumping my current project to the 0.7 version of this crate which has introduced the ConstantRef and TypeRef structs. Unfortunately a lot of my code does a whole bunch of pattern matching on things, for example: 

```rust
    let min = if let LlvmOperand::ConstantOperand(Constant::Float(Float::Double(val))) = min_ {
        val
    } else {
        Err(Error::NonConstantInputMin)?
    };
```

Obviously this code no longer compiles, and as far as I know, there is no way
to maintain this neat pattern matching thing. Instead, I'd have to add an inner
match, with additional handling of other constant types.

I know this is a hard problem to solve, so feel free to ignore it. If it's
something that may be interesting to others, I might look into working out a
solution.

**Comment by cdisselkoen** [comment]
Hi!

For myself, my own code (for instance in [Haybale](https://github.com/PLSysSec/haybale)) also does a lot of pattern matching on constants and types.  In this case here, I also don't know of a better way than adding an inner match and having to handle the other constant types.  For the case where we have something like 
(llvm-ir 0.6.0)
```
match operand.get_type() {
```
we can convert that to
```
match module.type_of(&operand).as_ref() {
```
with an explicit `as_ref()` call; it doesn't seem to work to just do
```
match &module.type_of(&operand) {
```

I realize that all of this is a little less ergonomic, but making these changes to Constant and Type really did cut the peak memory usage of `llvm-ir` almost in half in my testing (at least for large bitcode files), as well as improve the runtime performance of `Module::from_bc_path()`, so in my opinion the tradeoff in ergonomics is worth it here.  But I'm of course very interested in any suggestions for how to improve the ergonomics!

**Comment by cdisselkoen** [comment]
Closing this following the conversation in #7.  Thanks for the suggestions and for bringing this up!
