### ISSUE TITLE
Instanciating types for tests

### ISSUE THREAD

**Issue by TheZoq2** [cdisselkoen/llvm-ir#8]
Hello again.

I'm in the process of porting my code over to 0.7 and ran into a problem when trying to port my tests. Most of them do something like this:

```rust
let instruction = BitCast {
    operand: LlvmOperand::LocalOperand {
        name: "retval".into(),
        ty: Type::PointerType { // This no longer compiles
            pointee_type: Box::new(Type::NamedStructType {
                name: "struct.Result".into(),
                ty: None,
            }),
            addr_space: 0,
        },
    },
```

At first, I thought I would just be able to create a new typeref using
`TypeRef::new(Type::...)` but that seems to not be the case.

I also found the `TypesBuilder` and `Types` struct, however the TypesBuilder
seems to be private and `Types`, as far as I can tell, has no constructor.

Am I missing something here?

**Comment by cdisselkoen** [comment]
Sorry this wasn't more clear!  In 0.7, [`Module`](https://docs.rs/llvm-ir/0.7.1/llvm_ir/module/struct.Module.html) now has a `Types`, from which you should be able to get any `TypeRef` you want.  So your example would look something like this:
```rust
let instruction = BitCast {
    operand: LlvmOperand::LocalOperand {
        name: "retval".into(),
        ty: module.types.pointer_to(
            module.types.named_struct("Result").unwrap()
        ),
    },
};
```

You can also look through `llvm-ir`'s own tests (e.g. https://github.com/cdisselkoen/llvm-ir/blob/master/tests/basic_tests.rs) if that helps.

**Comment by TheZoq2** [comment]
Ah alright, I'll try that tomorrow :)
